# permissions for end users to view applicationrevisions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applicationrevision-viewer-role
rules:
- apiGroups:
  - feisty.paas.feisty.dev
  resources:
  - applicationrevisions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - feisty.paas.feisty.dev
  resources:
  - applicationrevisions/status
  verbs:
  - get
