# permissions for end users to edit applicationrevisions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applicationrevision-editor-role
rules:
- apiGroups:
  - feisty.paas.feisty.dev
  resources:
  - applicationrevisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - feisty.paas.feisty.dev
  resources:
  - applicationrevisions/status
  verbs:
  - get
